version: "3"

services:
  db:
    container_name: mongo
    image: mongo

  server:
    container_name: server
    build: server/
    restart: unless-stopped
    command: python ./main.py
    ports:
      - "5000:5000"
    environment:
      FLASK_PORT: 5000
      DB_URI: "mongodb://db:27017/db"
      WORKER_URI: "http://worker/"
    depends_on:
      - db

  worker:
    container_name: worker
    build: worker/
    restart: unless-stopped
    command: python ./main.py
    environment:
      FLASK_PORT: 80
      DB_URI: "mongodb://db:27017/db"
    depends_on:
      - server

  client:
    container_name: client
    build: client/
    ports:
      - "3000:80"
    depends_on:
      - server

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/default.conf:/etc/nginx/default.conf
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      CLIENT: "client:80"
      SERVER: "server:5000"
      PORT: "3000"
    depends_on:
      - client
      - server
