version: "3"

services:
  db:
    container_name: mongo
    image: mongo

  server:
    container_name: server
    build: server/
    restart: unless-stopped
    command: python ./app.py
    ports:
      - "5000:80"
    environment:
      FLASK_PORT: 80
      DB_URI: "mongodb://db:27017/db"
      WORKER_URI: "http://worker/"
    depends_on:
      - db

  worker:
    container_name: worker
    build: worker/
    restart: unless-stopped
    command: python ./app.py
    ports:
      - "5001:80"
    environment:
      FLASK_PORT: 80
      DB_URI: "mongodb://db:27017/db"
    depends_on:
      - server

  client:
    container_name: client
    build: client/
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      CLIENT_SERVER_URL: 'localhost'
      CLIENT_SERVER_PORT: '5000'

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      CLIENT: "client:80"
      SERVER: "server:80"
      PORT: "80"
    depends_on:
      - client
      - server
